### PR TITLE
GetGenreAsync bug fix

### LINKED ISSUE #44: GetGenreAsync
## Description
- GetGenreAsync should use ReadItemAsync instead of GetItemQueryIterator
- CosmosDetail class has hard coded values

### PR DESCRIPTION
**Pull request by bartr**
## Type of PR

- [ ] Documentation changes
- [X] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR
- Change GetGenreAsync to use ReadItemAsync instead of GetItemQueryIterator
- CosmosDetail class has hard coded values

## Issues Closed or Referenced
- Closes #44

### CODE REVIEW

File: src/app/Controllers/MoviesController.cs [hunk 1]
```diff
@@ -86,7 +86,7 @@ public async Task<IActionResult> GetMoviesAsync([FromQuery]string q = "", [FromQ
                 };
             }
 
-            catch (System.AggregateException age)
+            catch (AggregateException age)
```
Comment (aflinchb) [inline src/app/Controllers/MoviesController.cs:89]: Should make this change in the other controllers/files too (I saw it in ActorsController, FeaturedController, GenresController, and CosmosHealthCheck

**Review by aflinchb — APPROVED** [review]
